In [8]:
--**********************************************************************************--
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
-------------------------  DDL - Tables  ---------------------------------------------
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
USE Flight_Target;
GO
/*********************************************************/
/******************  Airport DIM DDL   ******************/
/*********************************************************/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'airports')
BEGIN
CREATE TABLE dim.airports(
	AIRPORT_ID nvarchar(50) NOT NULL,
	AIRPORT nvarchar(150) NOT NULL,
	CITY nvarchar(50) NOT NULL,
	STATE nvarchar(50) NOT NULL,
	COUNTRY nvarchar(50) NOT NULL,
	LATITUDE float NULL,
	LONGITUDE float NULL
);
	ALTER TABLE dim.airports
	ADD CONSTRAINT PK_airports PRIMARY KEY (AIRPORT_ID);
END;


/*********************************************************/
/******************  Airline DIM DDL   ******************/
/*********************************************************/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'airlines')
BEGIN
CREATE TABLE dim.airlines(
	AIRLINE_ID varchar(5) NOT NULL,
	AIRLINE nvarchar(50) NOT NULL,
)
;

	ALTER TABLE dim.airlines
	ADD CONSTRAINT PK_airlines PRIMARY KEY(AIRLINE_ID);
END;


/*********************************************************/
/******************  Calendar DDL  ***********************/
/*********************************************************/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'Calendar')
BEGIN
CREATE TABLE dim.Calendar
(
		pkCalendar INT NOT NULL,
		DateValue DATE NOT NULL,
		fYear INT NOT NULL,
		fMonthNu INT NOT NULL,
		fMonth Varchar(15) NOT NULL,
		fDay INT NOT NULL,
		fDayName varchar(15) NOT NULL,
		IsWeekDay varchar(10) NOT NULL,
		Weekday varchar(10) NOT NULL
);
	ALTER TABLE dim.Calendar
	ADD CONSTRAINT pk_Calendar_Julian PRIMARY KEY(pkCalendar);

	ALTER TABLE dim.Calendar
    ADD CONSTRAINT UC_Calendar UNIQUE (DateValue);
END
;

/*********************************************************/
/******************  Cancellations DDL  ***********************/
/*********************************************************/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dim' AND TABLE_NAME = 'Calendar')
BEGIN

CREATE TABLE dim.cancellations
(		CANCELID varchar(5) NOT NULL,
		Reasoning varchar(25) NOT NULL
	);

	ALTER TABLE dim.cancellations
	ADD CONSTRAINT pk_cancel_ID PRIMARY KEY(CANCELID)
	;
END


/*********************************************************/
/*********************************************************/
/*****  F. FACT TABLE - DIM DDL    ***********************/
/*********************************************************/
/*********************************************************/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'f' AND TABLE_NAME = 'FLIGHT_TABLE')
BEGIN
	CREATE TABLE f.FLIGHT_TABLE(
		FlightID INT /*Identity(1,1)*/ NOT NUll
		, fkCalendar INT NOT NULL
		, fkAIRLINE varchar(5) NOT NULL
		, fkORIGIN_AIRPORT nvarchar(50) NOT NULL 
		, DESTINATION_AIRPORT varchar(5) NOT NULL 
		, Scheduled_Departure int NOT NULL  
		, Departure int NOT NULL  
		, Departure_Delay_min int NOT NULL
		, Scheduled_Arrival int NOT NULL 
		, Arrival_time_local int NOT NULL
		, ARRIVAL_DELAY_min int NOT NULL
		, Flight_Length_min int
		, Total_Time int NOT NULL
		, DIVERTED int NULL
		, CANCELLED	int NULL
		, CANCELLATION_Reason varchar(5) NULL
		
);
	ALTER TABLE f.FLIGHT_TABLE
	ADD CONSTRAINT pk_FlightID PRIMARY KEY(FlightID);

	ALTER TABLE f.FLIGHT_TABLE
	ADD CONSTRAINT FT_Cal FOREIGN KEY (fkCalendar)
	REFERENCES Flight_Target.dim.Calendar

	ALTER TABLE f.FLIGHT_TABLE
	ADD CONSTRAINT FT_AirLi FOREIGN KEY(fkAIRLINE)
	REFERENCES Flight_Target.dim.airlines
END

/*
-- Had a lot of issues with the below 2 FK declarations. And I think I know why.
-- In Flight logs ORG column (fkOrigin_Airport), there is some airports located in
-- USA territories, like GUAM, that are not allocated a, 'ABC' name. They have a 
-- numeric naming concention '11111'. The numerics are NOT in the original source with Airline info

-- So the key wouldn't like that there is values in the fact table (fkORIGIN Airport)
-- but these values were not in the DIM table (AIRLINE_ID)

--SIMILAR situation for the cancellations. There is blanks on the cancellation reason fields, I tried NULL and
-- NOT NULL, but nothing worked for me. I spent days examining

		ALTER TABLE f.FLIGHT_TABLE
	ADD CONSTRAINT FT_AirPo FOREIGN KEY(fkORIGIN_AIRPORT)
	REFERENCES Flight_Target.dim.airports

	ALTER TABLE f.FLIGHT_TABLE
	ADD CONSTRAINT FT_cancelID FOREIGN KEY(CANCELLATION_Reason)
	REFERENCES Flight_Target.dim.cancellations

	*/